### ISSUE TITLE
South syncdb conflict

### ISSUE THREAD

**Issue by mrichnu** [alex/django-fixture-generator#3]
South overrides syncdb and won't create tables for apps it manages unless passed the --all flag.

**Comment by alex** [comment]
Thanks for filling a bug on this, Andrew and I discussed a solution, I just haven't implemented it yet.

**Comment by mrichnu** [comment]
I fixed it by just adding a migrate_all=True kwargument on line 91 of generate_fixture.py. I don't know git/github though so I didn't know how to upload a patch. Also wasn't sure how to test it, but it worked for me (IE whether or not South is enabled in my settings file, generate_fixture works with that kwarg)

**Comment by alex** [comment]
Good idea, I forgot Django can silently absord extra kwargs.  To get a patch just fork fixture-generator and commit it there, then I can pull your change in automatically.  If you don't want to fork it you can always just paste your udiff on paste.pocoo.org

**Comment by mrichnu** [comment]
forked, committed, and pushed. I hope I did the git part right.

**Comment by alex** [comment]
fixed in 47ef8208f2265c993d86, thanks
